# Site settings
title: 'Beto Ferreira'
description: 'Front-end Developer + UI/UX Engineer'
url: 'http://obetoferreira.github.io'
baseurl: '/obetoferreira/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Beto Ferreira'
  email: obetoferreira@gmail.com
  twitter_username: obetoferreira
  facebook_username: obetoferreira
  github_username:  obetoferreira
  linkedin_username:  obetoferreira

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
